In [138]:
import cv2
import numpy as np

In [141]:
imagen = cv2.imread("img/mano.jpeg", cv2.IMREAD_GRAYSCALE)
_,imagen_bin = cv2.threshold(imagen, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
cv2.imshow("Imagen", imagen_bin)
cv2.waitKey(0)

-1

In [140]:
# Matriz de prueba

imagen_bin = np.matrix([
    [1,1,1],
    [1,0,1],
    [1,1,1]
]).astype(np.uint8)
imagen_bin


matrix([[1, 1, 1],
        [1, 0, 1],
        [1, 1, 1]], dtype=uint8)

In [142]:
h, w = imagen_bin.shape
matriz_distancias = (h + w) * imagen_bin.astype(np.uint16)
matriz_distancias

array([[52274, 52274, 52274, ..., 52274, 52274, 52274],
       [52274, 52274, 52274, ..., 52274, 52274, 52274],
       [52274, 52274, 52274, ..., 52274, 52274, 52274],
       ...,
       [52274, 52274, 52274, ..., 52274, 52274, 52274],
       [52274, 52274, 52274, ..., 52274, 52274, 52274],
       [52274, 52274, 52274, ..., 52274, 52274, 52274]],
      shape=(286, 176), dtype=uint16)

In [143]:
# Primera pasada
for y in range(h):
    for x in range(w):
        norte = y - 1
        oeste = x - 1
        if norte < h and norte >= 0:
            pixel_norte = matriz_distancias[norte, x]
        else:
            pixel_norte = h + w
        if oeste < w and oeste >= 0:
            pixel_oeste = matriz_distancias[y, oeste]
        else:
            pixel_oeste = h + w
    
        matriz_distancias[y,x] = min(matriz_distancias[y,x], pixel_norte + 1, pixel_oeste + 1)

print(matriz_distancias)

[[463 463 463 ...  60  61  62]
 [463 464 464 ...  58  59  60]
 [463 464 465 ...  57  58  59]
 ...
 [180 174 171 ...  75  76  77]
 [181 175 172 ...  75  76  77]
 [182 176 173 ...  75  76  77]]


In [144]:
# Segunda Pasada
for y in range(h-1, -1, -1):
    for x in range(w-1, -1, -1):
        sur = y + 1
        este = x + 1
        if sur < h and sur >= 0:
            pixel_sur = matriz_distancias[sur, x]
        else:
            pixel_sur = h + w
        if este < w and este >= 0:
            pixel_este = matriz_distancias[y, este]
        else:
            pixel_este = h + w
        
        matriz_distancias[y,x] = min(matriz_distancias[y,x], pixel_sur + 1, pixel_este + 1)

print(matriz_distancias)

[[85 84 83 ... 48 49 50]
 [84 83 82 ... 47 48 49]
 [83 82 81 ... 46 47 48]
 ...
 [17 16 15 ... 75 76 77]
 [16 15 14 ... 75 76 77]
 [16 15 14 ... 75 76 77]]


In [145]:
matriz_distancias

array([[85, 84, 83, ..., 48, 49, 50],
       [84, 83, 82, ..., 47, 48, 49],
       [83, 82, 81, ..., 46, 47, 48],
       ...,
       [17, 16, 15, ..., 75, 76, 77],
       [16, 15, 14, ..., 75, 76, 77],
       [16, 15, 14, ..., 75, 76, 77]], shape=(286, 176), dtype=uint16)

In [147]:
matriz_distancias_2 = cv2.distanceTransform(imagen_bin, cv2.DIST_L1, 3)

In [148]:
(matriz_distancias - matriz_distancias_2).sum()

np.float32(0.0)

In [128]:
%pip install scikit-image

Note: you may need to restart the kernel to use updated packages.


In [146]:
from skimage.feature import peak_local_max
skeleton = np.zeros(imagen_bin.shape, dtype=np.uint8)
coords = peak_local_max(matriz_distancias, min_distance=1)
for coord in coords:
    skeleton[coord[0], coord[1]] = 255
cv2.imshow("Distancias", skeleton)
cv2.waitKey(0)

-1